import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "./globals.css";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import Home from '../app/(root)/(home)/page'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* Add any additional head elements here */}
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-hidden text-foreground bg-background`}
        >
          <ThemeProvider
            attribute='class'
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <SignedIn>
              <div className="flex flex-col min-h-screen">
                <Navbar />
                {/* <Home /> */}
                <main className="flex-1 w-full pb-10">
                  {children}
                </main>
              </div>
            </SignedIn>
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
          </ThemeProvider>
          <Toaster
            position="top-center"
            expand={false}
            richColors
            toastOptions={{
              style: {
                textAlign: 'center',
                display: 'flex',
                alignItems: 'center',
                gap: '8px'
              } as React.CSSProperties,
              classNames: {
                toast: 'flex flex-row items-center justify-center'
              }
            }}
          />
        </body>
      </html>
    </ConvexClerkProvider >
  );
}
